language: c++
sudo: required
dist: trusty
notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y zsh
  - sudo apt-get install -y libboost-dev

script:
  - ./config.sh
