language: c++
sudo: required
dist: trusty
notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y zsh
  - sudo apt-get install -y libboost-filesystem-dev libboost-regex-dev libboost-system-dev libboost-python-dev
  - sudo apt-get install -y libclang-dev

script:
  - ./config.sh
